/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HP
 */
public class Laboratory extends javax.swing.JFrame {

    /**
     * Creates new form Laboratory
     */
    public Laboratory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Pateint ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(29, 93, 70, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 255));
        jLabel2.setText("Pateints Test Detalis");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(222, 11, 211, 38);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Test name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(29, 273, 72, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Test Details");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(29, 371, 79, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Result");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(37, 479, 43, 17);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(168, 93, 200, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(168, 270, 200, 20);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(168, 479, 200, 20);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(285, 669, 83, 25);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Enter");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(427, 669, 71, 25);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(559, 669, 67, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("TestID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(29, 207, 47, 17);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(168, 207, 200, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Laboratristname");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(29, 527, 114, 28);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(168, 533, 200, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Labno");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(29, 599, 43, 17);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(168, 599, 200, 20);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient Name", "Testname", "Description", "Result", "Laboratristname", "TestID", "labno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(406, 479, 617, 93);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(168, 344, 200, 74);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Patient Name");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(29, 147, 93, 17);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(168, 147, 200, 20);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("search patient Test Details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(406, 89, 213, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/imgtty.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(461, 188, 0, 0);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/imgtty.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(490, 200, 280, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
     
        
        try {
           Statement s=DataBaseHospitalMS.getStatement(); 
           Statement s1=DataBaseHospitalMS.getStatement(); 
    s.executeUpdate("INSERT INTO test(Testname,Description,Result,Laboratristname,TestID,labno) VALUES('"+jTextField3.getText() + "','" + jTextField2.getText() + "','"+jTextField4.getText()+"','" + jTextField6.getText()+ "','" + jTextField5.getText()+"','" + jTextField7.getText()+"')");
     
   
         
    s.executeUpdate("INSERT INTO patients_test(PatientID,TestID) VALUES('"+jTextField1.getText()+"','"+jTextField5.getText()+"')");
       JOptionPane.showMessageDialog(null, "INSERT Successfull Test..!");
       
        } catch (Exception ex) {
            //Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Statement st = DataBaseHospitalMS.getStatement();
 
       try {
          
           
           
        st.executeUpdate("UPDATE test SET Testname='" + jTextField3.getText() + "', Description='" + jTextField2.getText()+ "', Result='" +jTextField4.getText() + "', Laboratristname='" + jTextField6.getText() + "', TestID='" + jTextField5.getText() +"',labno='" + jTextField7.getText()+"' WHERE TestID='" + jTextField5.getText()+ "'");
        //Testname,Description,Result,Laboratristname,TestID,labno,PatientID= '" + jTextField3.getText()+jTextField2.getText()+jTextField4.getText()+jTextField6.getText()+jTextField5.getText()+jTextField7.getText()+jTextField1.getText()+ "' WHERE PateintID='" + jTextField1.getText()+ "'");
         JOptionPane.showMessageDialog(null, "UPDATE Successfull Test..!");
       } catch (Exception ex) {
           
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextField1.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        jTextField5.setText("");
        jTextField7.setText("");
      jTextField2.setText("");
      jTextField8.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
   DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        int selectedRowIndex=jTable1.getSelectedRow();
         jTextField8.setText(model.getValueAt(selectedRowIndex,0).toString());
        jTextField3.setText(model.getValueAt(selectedRowIndex,1).toString());
        jTextField2.setText(model.getValueAt(selectedRowIndex,2).toString());
           jTextField4.setText(model.getValueAt(selectedRowIndex,3).toString());
        
              jTextField6.setText(model.getValueAt(selectedRowIndex,4).toString());
                jTextField5.setText(model.getValueAt(selectedRowIndex,5).toString());
                  jTextField7.setText(model.getValueAt(selectedRowIndex,6).toString());
                     
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       Statement s=DataBaseHospitalMS.getStatement();
           
        try {
       ResultSet       rs = s.executeQuery("SELECT patients.PateintName,test.Testname,test.Description,test.Result,test.Laboratristname,test.TestID,test.labno FROM test right join  patients_test on test.TestID=patients_test.TestID right join patients on patients_test.PatientID=patients.PateintID  WHERE patients.PateintID = '" + jTextField1.getText() + "'");
       jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
        } catch (SQLException ex) {
            Logger.getLogger(Laboratory.class.getName()).log(Level.SEVERE, null, ex);
        }
// AND Specialization LIKE '%'"+jComboBox1.getSelectedItem()+"'%'");
            
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laboratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laboratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laboratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laboratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laboratory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
