/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Login extends javax.swing.JFrame {

    
    public Login() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 102, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Pharmasist");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(10, 280, 120, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Receptionist");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(140, 280, 130, 30);

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Doctor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(280, 280, 90, 30);

        jButton4.setBackground(new java.awt.Color(0, 102, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Laboratarist");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(380, 280, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("LOGIN AS");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(280, 220, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("User name:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(90, 110, 80, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(90, 160, 90, 20);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(210, 110, 290, 30);
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(210, 160, 290, 30);

        jButton6.setBackground(new java.awt.Color(0, 102, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Doctor");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(280, 280, 90, 30);

        jButton7.setBackground(new java.awt.Color(51, 51, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Admin");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(520, 280, 90, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/img456.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, -20, 650, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     // Statement s=DataBaseHospitalMS.getStatement();
      try{ if(jTextField1.getText().length()==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields","WARNING",JOptionPane.WARNING_MESSAGE);
        }
        else if(jPasswordField1.getPassword().length==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields","WARNING",JOptionPane.WARNING_MESSAGE);
        }
        else{
          char[] pass = jPasswordField1.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass); 
            String user=jTextField1.getText();
       //  ResultSet gh =  s.executeQuery("SELECT * from employee where Username='"+jTextField1.getText()+"'and password='"+jPasswordField1+"' and Position='Pharmasist'");
          
      if (code(user,pwd,"Pharmasist")){
          Pharmacy p=new Pharmacy();
       p.setVisible(true);
        }
      
      else{
       JOptionPane.showMessageDialog(null,"Incorrect Login");
      
      }
        }}
    catch(Exception e){
            
            }      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try{ if(jTextField1.getText().length()==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields","WARNING",JOptionPane.WARNING_MESSAGE);
        }
        else if(jPasswordField1.getPassword().length==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields","WARNING",JOptionPane.WARNING_MESSAGE);
        }
        else{
          char[] pass = jPasswordField1.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass); 
            String user=jTextField1.getText();
       //  ResultSet gh =  s.executeQuery("SELECT * from employee where Username='"+jTextField1.getText()+"'and password='"+jPasswordField1+"' and Position='Pharmasist'");
          
      if (code(user,pwd,"Receptionist")){
          Reception p=new Reception();
       p.setVisible(true);
        }
      
      else{
       JOptionPane.showMessageDialog(null,"Incorrect Login");
      
      }
        }}
    catch(Exception e){
            
            }    
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   // Checking for empty field
        try{ if(jTextField1.getText().length()==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields","WARNING",JOptionPane.WARNING_MESSAGE);
        }
        else if(jPasswordField1.getPassword().length==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields","WARNING",JOptionPane.WARNING_MESSAGE);
        }
        else{
          char[] pass = jPasswordField1.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass); 
            String user=jTextField1.getText();
       //  ResultSet gh =  s.executeQuery("SELECT * from employee where Username='"+jTextField1.getText()+"'and password='"+jPasswordField1+"' and Position='Pharmasist'");
          
      if (code(user,pwd,"Doctor")){
          Doctor p=new Doctor();
       p.setVisible(true);
        }
      
      else{
       JOptionPane.showMessageDialog(null,"Incorrect Login");
      
      }
        }}
    catch(Exception e){
            
            } 
                    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try{ if(jTextField1.getText().length()==0){ 
        JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields","WARNING",JOptionPane.WARNING_MESSAGE);
        }
        else if(jPasswordField1.getPassword().length==0){  // Checking for empty field
      JOptionPane.showMessageDialog(null, "Empty fields detected ! Please fill up all fields","WARNING",JOptionPane.WARNING_MESSAGE);
        }
        else{
          char[] pass = jPasswordField1.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass); 
            String user=jTextField1.getText();
       //  ResultSet gh =  s.executeQuery("SELECT * from employee where Username='"+jTextField1.getText()+"'and password='"+jPasswordField1+"' and Position='Pharmasist'");
          
      if (code(user,pwd,"Laboratrist")){
          Laboratory l=new Laboratory();
       l.setVisible(true);
        }
      
      else{
       JOptionPane.showMessageDialog(null,"Incorrect Login");
      
      }
        }}
    catch(Exception e){
            
            }         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
  try {
 // Statement stat=DataBaseHospitalMS.getStatement();
          //  ResultSet     result ;
          //  result= stat.executeQuery("Select username,password from admin where username=? AND password=?");
            Connection        con=null;
PreparedStatement pst=null;
ResultSet rs=null;          
            
      
       //  Statement st = DataBaseHospitalMS.getStatement(); 
      Connection   conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitall?" + "user=root&password=");   
       pst = conn.prepareStatement("Select username,password from admin where username=? AND password=?");
       pst.setString(1, jTextField1.getText());
       pst.setString(2, jPasswordField1.getText());
       rs = pst.executeQuery(); 
            
        if(rs.next()){
            
         
        JOptionPane.showMessageDialog(null, "successful login");
        signIN d=new signIN();
        d.setVisible(true);
        this.dispose();
        
        }
            
        else{
            JOptionPane.showMessageDialog(null, "username or password incorrect!!!","ERROR",JOptionPane.ERROR_MESSAGE);
          
        }}
         catch (SQLException ex) {
            System.out.println("Cannot find");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

   /** private boolean validate_login(String user, String pwd) {
       try {
            
       Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitall?" + "user=root&password=");     
       PreparedStatement pst = conn.prepareStatement("Select * from employee where Username=? and password=? and PositionCode=);
       pst.setString(1, user); 
       pst.setString(2, pwd);
      // pst.setString(3,posi);
       ResultSet rs = pst.executeQuery();                        
       if(rs.next())            
           return true;    
       else
           return false;
            
            
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }**/

private boolean code(String user,String pwd,String code){      
            
        try {
           Statement st = DataBaseHospitalMS.getStatement(); 
      Connection   conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospitall?" + "user=root&password=");
            PreparedStatement pst = conn.prepareStatement("Select Username,password,Position from employee where Username=? and password=? and Position=?");
      
            
            pst.setString(1, user); 
      pst.setString(2, pwd);
      pst.setString(3, code);
       ResultSet rs = pst.executeQuery();                        
       if(rs.next())return true; 
       else 
           return false;
        } catch (Exception e) {
       e.printStackTrace();
            return false;    // Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        }

}
